name: jobfinder2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  connectivity: ^3.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.0.0
  file_picker: ^8.0.3
  provider: ^6.0.5
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
